const REDUCER = 'users';

export const GET_USER_LIST_REQUEST = `${REDUCER}/GET_USER_LIST_REQUEST`;
export const GET_USER_LIST_SUCCESS = `${REDUCER}/GET_USER_LIST_SUCCESS`;
export const GET_USER_LIST_FAILURE = `${REDUCER}/GET_USER_LIST_FAILURE`;

export const GET_USER_REQUEST = `${REDUCER}/GET_USER_REQUEST`;
export const GET_USER_SUCCESS = `${REDUCER}/GET_USER_SUCCESS`;
export const GET_USER_FAILURE = `${REDUCER}/GET_USER_FAILURE`;

export default REDUCER;
